name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Enables running workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository under $GITHUB_WORKSPACE so job can access it
      - uses: actions/checkout@v3

      - name: Linting
        run: $GITHUB_WORKSPACE/gradlew ktlintCheck

      - name: Tests
        run: $GITHUB_WORKSPACE/gradlew test
