name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Unit Tests

    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Linting
        run: gradle ktlintCheck

      - name: Unit Tests
        run: gradle test
