name: All Checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Linting

    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Linting
        run: ./gradlew ktlintCheck

  test:
    name: Unit Tests

    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Java Version
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
          cache: gradle

      - name: Unit Tests
        run: ./gradlew test
